config/routes.rb
Rails.application.routes.draw do
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to "/items/#{@item.id}"
  end

  def edit
   @item = Item.find(params[:id])
  end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to "/items/#{@item.id}"
 end

 def destroy
   @item = Item.destroy(params[:id])
   @item.destroy
   redirect_to "/items"
 end

 private

 def item_params
   params.require(:item).permit(:name, :description, :price, :seller_id,:email, :image_url)
 end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>商品情報更新フォーム</h1>
<%= form_for @item, url: {action: :update} do |f| %>
  <p>
    商品名：<br />
    <%= f.text_field :name %>
  </p>
  <p>
    商品詳細：<br />
    <%= f.text_area :description %>
  </p>
  <p>
    価格：<br />
    <%= f.number_field :price %>
  </p>
  <p>
    売り主ＩＤ：<br />
    <%= f.text_field :seller_id %>
  </p>
  <p>
    電子メール：<br />
    <%= f.text_field :email %>
    </p>
  <p>
    商品画像ＵＲＬ：<br />
    <%= f.text_field :image_url %>
  </p>
  <%= f.submit "更新" %>
<% end %>

app/views/items/index.html.erb
<h1>出品商品一覧</h1>
<% @items.each do |item| %>
  <li><%= link_to item.name, item_path(item) %></li>
<% end %>
<a href="<%= new_item_path %>"出品する</a>
<%= link_to "出品", new_item_path %>

app/views/items/new.html.erb
<h>商品登録フォーム</h>
<%= form_for @item do |f| %>
<p>
  商品名:<br>
  <%= f.text_field :name %>
</p>
<p>
    商品詳細：<br>
    <%= f.text_area :description %>
  </p>
  <p>
    価格：<br>
    <%= f.number_field :price %>
  </p>
  <p>
    売り主ＩＤ：<br>
    <%= f.number_field :seller_id %>
  </p>
  <p>
    電子メール：<br>
    <%= f.text_field :email %>
  </p>
  <p>
    商品画像ＵＲＬ：<br>
    <%= f.text_field :image_url %>
  </p>
  <%= f.submit "登録" %>
<% end %>

app/views/items/show.html.erb
<p>
  <b>商品名:<%= @item.name %></b>
<p/>
<p>
  <b>商品詳細:<%= @item.description %></b>
<p/>
<p>
  <b>価格:<%= @item.price %></b>
<p/>
<p>
  <b>売り手ID:<%= @item.seller_id %></b>
<p/>
<p>
  <b>電子メール:<%= @item.email %></b>
<p/>
<p>
  <%= imag_tag @item.image_url %>
</p>

  <p>
  <%= link_to "編集", edit_item_path(@item) %>
</p>
 <p>
  <%= link_to "削除",item_path(@item), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>